"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

import { usePathname } from "next/navigation";

export function Links() {
  const pathname = usePathname();

  return (
    <nav>
      <ul>
        <li>
          <Link className={`link ${pathname === "/" ? "active" : ""}`} href="/">
            Home
          </Link>
        </li>
        <li>
          <Link
            className={`link ${pathname === "/about" ? "active" : ""}`}
            href="/about"
          >
            About
          </Link>
        </li>
      </ul>
    </nav>
  );
}
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "MIQ",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <Link
          className={pathname === "/secondRoute" ? "customized" : ""}
          href="/secondRoute"
        >
          second route link
        </Link>
        <br />
        <Link href="/third#Montasser">third route link</Link>
        {children}
      </body>
    </html>
  );
}
